name: "TypeScript"

on:
  push:
    branches:
      - future
    paths:
      - typescript/**
  pull_request:
    branches:
      - main
    paths:
      - typescript/**

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        id: install dependencies
        working-directory: "./typescript"
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Check diff
        id: check diff
        working-directory: "./typescript"
        run: git diff --exit-code
